channels:
  - conda-forge
  - defaults
dependencies:
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip
category: dev
platforms:
  - linux-64
  - osx-64
  - win-64
  - osx-arm64  # For Apple Silicon, e.g. M1/M2
  - linux-aarch64  # aka arm64, use for Docker on Apple Silicon
  - linux-ppc64le
