channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - yapf
  - jupyter
  - pandas
  - matplotlib
  - geopandas
  - plotly
  - pip
platforms:
  - linux-64
  - osx-64
  - win-64
  - osx-arm64  # For Apple Silicon, e.g. M1/M2
  - linux-aarch64  # aka arm64, use for Docker on Apple Silicon
  - linux-ppc64le